apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - redis.yaml
  - hpa.yaml

images:
  - name: taskflow-api
    newName: REPLACED_BY_JENKINS/taskflow-api
    newTag: placeholder
