apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-redis
  labels:
    app: taskflow-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-redis
  template:
    metadata:
      labels:
        app: taskflow-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: taskflow-redis
  labels:
    app: taskflow-redis
spec:
  selector:
    app: taskflow-redis
  ports:
    - port: 6379
      targetPort: 6379
